### ISSUE TITLE
Header files cannot be found

### ISSUE THREAD

**Issue by berat66** [eclipse/paho.mqtt.cpp#103]
I am trying to test the API by creating a client, so I include the client.h file. When I try to compile, the compiler can't find the following headers in file async_client.h:

#include "mqtt/token.h"
#include "mqtt/delivery_token.h"
#include "mqtt/iclient_persistence.h"
#include "mqtt/iaction_listener.h"
#include "mqtt/exception.h"
#include "mqtt/message.h"
#include "mqtt/callback.h"
#include "mqtt/iasync_client.h"

This files are all copied into /usr/local/include while installing. So because they are not in a folder named mqtt, the header files arent found. Compiling the shared libraries worked, though.
Am I missing something or is this a bug?

**Comment by fpagliughi** [comment]
There was a fix recently for the CMake build (PR #65). That is in the 'develop' branch.

Which build system are you using? CMake, autotools, or GNU make?

**Comment by berat66** [comment]
I have used autotools for building. I have copied the folder mqtt into /usr/local/include, which helped resolving my problem. But I think, it should be fixed in the release/master branch

**Comment by fpagliughi** [comment]
True enough. Plus I was mistaken. #65 fixed the CMake build. The autotools build was still incorrect in both branches. Now it is fixed in both.
