### ISSUE TITLE
Unable to load server certificate

### ISSUE THREAD

**Issue by tgill880** [eclipse/paho.mqtt.cpp#222]
System: Raspberry Pi 3B+, lastest buster.

I am trying to run the `ssl_publish.cpp` sample program.

I get an error when launching `mosquitto` per instructions in the program.
```
$ mosquitto -c test/tls-testing/mosquitto.conf 
1571371038: mosquitto version 1.5.7 starting
1571371038: Config loaded from test/tls-testing/mosquitto.conf.
1571371038: Opening ipv4 listen socket on port 1883.
1571371038: Opening ipv6 listen socket on port 1883.
1571371038: Opening ipv4 listen socket on port 18883.
1571371038: Opening ipv6 listen socket on port 18883.
1571371038: Opening ipv4 listen socket on port 18884.
1571371038: Opening ipv6 listen socket on port 18884.
1571371038: Error: Unable to load server certificate "test/ssl/server.crt". Check certfile.
1571371038: Error: Protocol not available
```
The file definitely exists. So either the file is corrupted, or there is a protocol not supported on my system. Note that `mosquitto` is at `version 1.5.7`.

In comparison, the exact same command works correctly on my MacBook Pro
```
$ mosquitto -c test/tls-testing/mosquitto.conf 
1571371495: mosquitto version 1.6.7 starting
1571371495: Config loaded from test/tls-testing/mosquitto.conf.
1571371495: Opening ipv6 listen socket on port 1883.
1571371495: Opening ipv4 listen socket on port 1883.
1571371495: Opening ipv6 listen socket on port 18883.
1571371495: Opening ipv4 listen socket on port 18883.
1571371495: Opening ipv6 listen socket on port 18884.
1571371495: Opening ipv4 listen socket on port 18884.
1571371495: Opening ipv6 listen socket on port 18885.
1571371495: Opening ipv4 listen socket on port 18885.
1571371495: Opening ipv6 listen socket on port 18886.
1571371495: Opening ipv4 listen socket on port 18886.
1571371495: Opening ipv6 listen socket on port 18887.
1571371495: Opening ipv4 listen socket on port 18887.
1571371495: Opening ipv6 listen socket on port 18888.
1571371495: Opening ipv4 listen socket on port 18888.
```
Note that `mosquitto` is at `version 1.6.7`.

Any comments appreciated.

**Comment by EthsonLiu** [comment]
Can you try update version to 1.6.7 in your Raspberry? If it can't solve your problem, try use the whole path.

**Comment by fpagliughi** [comment]
Did you get this resolved? If so, let us know. If not, maybe first look to make sure the file properly made it onto the board and didn’t get mangled. Then perhaps try a different version of mosquito if you can (if you’re not required to use that specific version, for some reason).

If it’s still giving you trouble, it may be better to ask the question on a mosquito forum or mailing list, like here:
https://www.eclipse.org/forums/index.php?t=thread&frm_id=270

**Comment by jedi7** [comment]
Hi, I'm hitting the same problem.
Strange thing is, when I use older certificate, then it works. If I use newer then it fails.
```
mosquitto[22854]: mosquitto version 1.6.7 starting
...
mosquitto[22854]: Error: Unable to load server key file "/etc/mosquitto/certs/mqtt_srv.key". Check keyfile.
mosquitto[22854]: Error: Protocol not available
```

**Comment by jedi7** [comment]
I fixed it by regenerating the CA and crt + key. And checked them by procedure here: https://kb.wisc.edu/middleware/4064
So, from my point it is problem with certs.

**Comment by PSGXerus** [comment]
I'm having the same problem. And I also regenerated CA and the keys and checked them as @jedi7 recommended. The problem is still there.

**Comment by PSGXerus** [comment]
I did exactly follow this guide and was able to resolve the issue: https://mosquitto.org/man/mosquitto-tls-7.html
